[build]
  publish = "frontend/public" # Set to the folder where your static assets are generated

[dev]
  command = "node src/server.js" # Start the Express server during development

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200