[build]
  publish = "src/views/ejs" # Set to the folder where your static assets are generated

[dev]
  command = "node src/server.js" # Start the Express server during development

[[redirects]]
  from = "/*"
  to = "/src/controllers/homeController/:splat"
  status = 200
  force = true