[build]
  command = "npm run start"
[dev]
  command = "node src/server.js" # Start the Express server during development

[[redirects]]
  from = "/"
  to = "/src/controllers/homeController"
  status = 200
  force = true